"""Added Notification model

Revision ID: dcb7ea383336
Revises: ed8938ab98d2
Create Date: 2024-11-29 17:17:55.826272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb7ea383336'
down_revision = 'ed8938ab98d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sendDate', sa.DateTime(), nullable=True))
        batch_op.drop_column('send_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('sendDate')

    # ### end Alembic commands ###
