"""Naming Convention Fix

Revision ID: ea65888afbc4
Revises: 91a4a7f02a7c
Create Date: 2024-12-02 13:54:24.458504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea65888afbc4'
down_revision = '91a4a7f02a7c'
branch_labels = None
depends_on = None


def upgrade():
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
