"""Added Notification model

Revision ID: ed8938ab98d2
Revises: a6e59b3510a5
Create Date: 2024-11-29 17:14:18.995115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8938ab98d2'
down_revision = 'a6e59b3510a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('unavailability', schema=None) as batch_op:
        batch_op.alter_column('employeeID',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unavailability', schema=None) as batch_op:
        batch_op.alter_column('employeeID',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('send_date')

    # ### end Alembic commands ###
