name: Python Tests

on:
  push:
    branches:
      - main    # Run tests on pushes to the main branch
  pull_request:
    branches:
      - main    # Run tests on pull requests targeting main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run pytest
        run: |
          pytest --maxfail=5 --disable-warnings --cov=src
